<script setup lang="ts">
definePageMeta({
  layout: "empty",
});

const sections = [
  {
    title: "Interpretation",
    content: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
  },
  {
    title: "Definitions",
    content: [
      "Account means a unique account created for You to access our Service or parts of our Service.",
      "Affiliate means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
      "Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Sole Proprietorship , 1-47, Pusat Perniagaan Perdana Jaya, 14000 Bukit Mertajam.",
      "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
      "Country refers to: Malaysia",
      "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
      "Personal Data is any information that relates to an identified or identifiable individual.",
      "Service refers to the Website.",
      "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
      "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
      "Website refers to STUDIO RAYA PENANG, accessible from penang.fotoraya.com",
      "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
    ]
  },
  {
    title: "Types of Data Collected",
    content: [
      "Personal Data",
      "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
      "• Email address",
      "• First name and last name",
      "• Phone number",
      "• Usage Data",
      "\nUsage Data",
      "Usage Data is collected automatically when using the Service.",
      "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
      "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
      "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device."
    ]
  },
  {
    title: "Tracking Technologies and Cookies",
    content: [
      "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:",
      "\nCookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.",
      "\nWeb Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).",
      "\nCookies can be \"Persistent\" or \"Session\" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.",
      "\nWe use both Session and Persistent Cookies for the purposes set out below:",
      "\nNecessary / Essential Cookies",
      "Type: Session Cookies",
      "Administered by: Us",
      "Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.",
      "\nCookies Policy / Notice Acceptance Cookies",
      "Type: Persistent Cookies",
      "Administered by: Us",
      "Purpose: These Cookies identify if users have accepted the use of cookies on the Website.",
      "\nFunctionality Cookies",
      "Type: Persistent Cookies",
      "Administered by: Us",
      "Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
    ]
  },
  {
    title: "Use of Your Personal Data",
    content: [
      "The Company may use Personal Data for the following purposes:",
      "• To provide and maintain our Service, including to monitor the usage of our Service.",
      "• To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
      "• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
      "• To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
      "• To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
      "• To manage Your requests: To attend and manage Your requests to Us.",
      "• For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
      "• For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience."
    ]
  },
  {
    title: "Retention of Your Personal Data",
    content: [
      "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
      "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods."
    ]
  },
  {
    title: "Security of Your Personal Data",
    content: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."
  },
  {
    title: "Children's Privacy",
    content: [
      "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
      "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information."
    ]
  },
  {
    title: "Changes to this Privacy Policy",
    content: [
      "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
      "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the \"Last updated\" date at the top of this Privacy Policy.",
      "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page."
    ]
  }
];
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <div class="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <!-- Back Button -->
      <div class="mb-8">
        <NuxtLink 
          to="/" 
          class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
        >
          <svg class="w-5 h-5 mr-2 -ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
          </svg>
          Back to Home
        </NuxtLink>
      </div>

      <div class="bg-white shadow-sm rounded-lg p-6 sm:p-8">
        <!-- Header -->
        <div class="text-center mb-12">
          <h1 class="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
          <p class="text-gray-600">Last updated: February 25, 2025</p>
        </div>

        <!-- Introduction -->
        <div class="prose prose-slate max-w-none mb-12">
          <p class="text-gray-700">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p class="text-gray-700">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
          </p>
        </div>

        <!-- Policy Sections -->
        <div class="space-y-12">
          <template v-for="(section, index) in sections" :key="index">
            <section class="border-b border-gray-200 pb-8 last:border-0">
              <h2 class="text-2xl font-semibold text-gray-900 mb-4">{{ section.title }}</h2>
              <div class="prose prose-slate max-w-none">
                <template v-if="Array.isArray(section.content)">
                  <p v-for="(paragraph, pIndex) in section.content" 
                     :key="pIndex"
                     class="text-gray-700 whitespace-pre-line mb-3">
                    {{ paragraph }}
                  </p>
                </template>
                <p v-else class="text-gray-700">{{ section.content }}</p>
              </div>
            </section>
          </template>
        </div>

        <!-- Contact Section -->
        <div class="mt-12 pt-8 border-t border-gray-200">
          <h2 class="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
          <p class="text-gray-700">
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <div class="mt-4 space-y-2">
            <p class="text-gray-700">
              By visiting our website: <a href="https://penang.fotoraya.com" class="text-blue-600 hover:text-blue-800">penang.fotoraya.com</a>
            </p>
            <p class="text-gray-700">
              By phone number: <a href="tel:01162667017" class="text-blue-600 hover:text-blue-800">01162667017</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
